name: Alice CI

on:
  push:
    branches:
      - main

env:
  GIT_USER: AliceSchuberg
  GIT_EMAIL: 49569035+AliceSchuberg@users.noreply.github.com
  THEME_REPO: iissnan/hexo-theme-next
  THEME_BRANCH: master
  DEPLOY_REPO: AliceSchuberg/aliceschuberg.github.io
  DEPLOY_BRANCH: release

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest #windows-latest /  macos-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [16.18.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
#      - name: Checkout files
#        uses: Bhacaz/checkout-files@v2
#        with:
#          files: src

      - name: Checkout theme repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.THEME_REPO }}
          ref: ${{ env.THEME_BRANCH }}
          path: themes/next

      - name: Checkout deploy repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.DEPLOY_REPO }}
          ref: ${{ env.DEPLOY_BRANCH }}
          path: .deploy_git

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          sudo timedatectl set-timezone "America/New_York"
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL

      - name: Install dependencies
        run: |
          npm install ./src

      - name: Deploy hexo
        run: |
          cd src
          npm run deploy